// <auto-generated/>
// Emik.SourceGenerators.Tattoo, v2.0.7
#pragma warning disable
extern alias core;
global using Action = System.Action;
global using Activator = System.Activator;
global using ArgumentOutOfRangeException = System.ArgumentOutOfRangeException;
global using Array = System.Array;
global using AssemblyBuilder = System.Reflection.Emit.AssemblyBuilder;
global using BindingFlags = System.Reflection.BindingFlags;
global using CallerFilePathAttribute = System.Runtime.CompilerServices.CallerFilePathAttribute;
global using Camera = core::UnityEngine.Camera;
global using Color = core::UnityEngine.Color;
global using Component = core::UnityEngine.Component;
global using ConstantExpression = System.Linq.Expressions.ConstantExpression;
global using Delegate = System.Delegate;
global using EditorBrowsableAttribute = System.ComponentModel.EditorBrowsableAttribute;
global using EditorBrowsableState = System.ComponentModel.EditorBrowsableState;
global using Enum = System.Enum;
global using Enumerable = System.Linq.Enumerable;
global using Environment = System.Environment;
global using Exception = System.Exception;
global using Expression = System.Linq.Expressions.Expression;
global using GameObject = core::UnityEngine.GameObject;
global using Guid = System.Guid;
global using HarmonyMethod = HarmonyLib.HarmonyMethod;
global using HarmonyPatch = HarmonyLib.HarmonyPatch;
global using HarmonyPatchType = HarmonyLib.HarmonyPatchType;
global using HarmonyPostfix = HarmonyLib.HarmonyPostfix;
global using HarmonyPrefix = HarmonyLib.HarmonyPrefix;
global using IEnumerable = System.Collections.IEnumerable;
global using IEnumerator = System.Collections.IEnumerator;
global using ILGenerator = System.Reflection.Emit.ILGenerator;
global using IList = System.Collections.IList;
global using Image = UnityEngine.UI.Image;
global using InvalidOperationException = System.InvalidOperationException;
global using LambdaExpression = System.Linq.Expressions.LambdaExpression;
global using LayerMask = core::UnityEngine.LayerMask;
global using Logger = HarmonyLib.Tools.Logger;
global using Math = System.Math;
global using Mathf = core::UnityEngine.Mathf;
global using MemoryExtensions = System.MemoryExtensions;
global using MemberInfo = System.Reflection.MemberInfo;
global using MemoryStream = System.IO.MemoryStream;
global using MethodAttributes = System.Reflection.MethodAttributes;
global using MethodCallExpression = System.Linq.Expressions.MethodCallExpression;
global using MethodBase = System.Reflection.MethodBase;
global using MethodInfo = System.Reflection.MethodInfo;
global using MonoBehaviour = core::UnityEngine.MonoBehaviour;
global using NotNullWhenAttribute = System.Diagnostics.CodeAnalysis.NotNullWhenAttribute;
global using NotSupportedException = System.NotSupportedException;
global using Object = core::UnityEngine.Object;
global using OpCode = System.Reflection.Emit.OpCode;
global using OpCodes = System.Reflection.Emit.OpCodes;
global using ParameterAttributes = System.Reflection.ParameterAttributes;
global using ParameterInfo = System.Reflection.ParameterInfo;
global using Patch = (
    System.Reflection.MethodInfo? Target,
    System.Reflection.MethodInfo? Impl,
    HarmonyLib.HarmonyPatchType Type
);
global using Path = System.IO.Path;
global using PureAttribute = System.Diagnostics.Contracts.PureAttribute;
global using Random = core::UnityEngine.Random;
global using Resources = core::UnityEngine.Resources;
global using SortingGroup = core::UnityEngine.Rendering.SortingGroup;
global using SpriteMaskInteraction = core::UnityEngine.SpriteMaskInteraction;
global using SpriteRenderer = core::UnityEngine.SpriteRenderer;
global using StackFrame = System.Diagnostics.StackFrame;
global using Stream = System.IO.Stream;
global using StreamReader = System.IO.StreamReader;
global using StringBuilder = System.Text.StringBuilder;
global using StringComparer = System.StringComparer;
global using StringComparison = System.StringComparison;
global using Time = core::UnityEngine.Time;
global using Timeout = System.Threading.Timeout;
global using Transform = core::UnityEngine.Transform;
global using Type = System.Type;
global using TypeAttributes = System.Reflection.TypeAttributes;
global using Quaternion = core::UnityEngine.Quaternion;
global using UnaryExpression = System.Linq.Expressions.UnaryExpression;
global using Unsafe = System.Runtime.CompilerServices.Unsafe;
global using ValueTuple = System.ValueTuple;
global using Vector2 = core::UnityEngine.Vector2;
global using Vector2Int = core::UnityEngine.Vector2Int;
global using Vector3 = core::UnityEngine.Vector3;
global using Vector3Int = core::UnityEngine.Vector3Int;

[assembly: NullGuard(ValidationFlags.None)]
